;;;
;;; Copyright © 2022 Jiri Spacek <spacek@stokorec.cz>
;;;;;;
;;; The Work is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 3 of the License, or (at
;;; your option) any later version.
;;;
;;; The Work is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with The Work.  If not, see <http://www.gnu.org/licenses/>.

(define-module (personal packages emacs-xyz)
    #:use-module ((guix licenses) #:prefix license:)
    #:use-module (guix packages)
    #:use-module (guix cvs-download)
    #:use-module (guix download)
    #:use-module (guix deprecation)
    #:use-module (guix bzr-download)
    #:use-module (guix gexp)
    #:use-module (guix i18n)
    #:use-module (guix git-download)
    #:use-module (guix hg-download)
    #:use-module (guix build-system gnu)
    #:use-module (guix build-system cmake)
    #:use-module (guix build-system copy)
    #:use-module (guix build-system emacs)
    #:use-module (guix build-system perl)
    #:use-module (guix build-system trivial)
    #:use-module (gnu packages)
    #:use-module (gnu packages admin)
    #:use-module (gnu packages aspell)
    #:use-module (gnu packages audio)
    #:use-module (gnu packages emacs-xyz)
    #:use-module (gnu packages bash)
    #:use-module (gnu packages chez)
    #:use-module (gnu packages cmake)
    #:use-module (gnu packages code)
    #:use-module (gnu packages cpp)
    #:use-module (gnu packages curl)
    #:use-module (gnu packages databases)
    #:use-module (gnu packages dictionaries)
    #:use-module (gnu packages djvu)
    #:use-module (gnu packages ebook)
    #:use-module (gnu packages emacs)
    #:use-module (gnu packages enchant)
    #:use-module (gnu packages fonts)
    #:use-module (gnu packages freedesktop)
    #:use-module (gnu packages games)
    #:use-module (gnu packages gawk)
    #:use-module (gnu packages golang)
    #:use-module (gnu packages guile)
    #:use-module (gnu packages gtk)
    #:use-module (gnu packages gnome)
    #:use-module (gnu packages graphviz)
    #:use-module (gnu packages haskell-apps)
    #:use-module (gnu packages ibus)
    #:use-module (gnu packages java)
    #:use-module (gnu packages julia-xyz)
    #:use-module (gnu packages ncurses)
    #:use-module (gnu packages networking)
    #:use-module (gnu packages python)
    #:use-module (gnu packages python-xyz)
    #:use-module (gnu packages telephony)
    #:use-module (gnu packages terminals)
    #:use-module (gnu packages tex)
    #:use-module (gnu packages texinfo)
    #:use-module (gnu packages tcl)
    #:use-module (gnu packages tls)
    #:use-module (gnu packages tree-sitter)
    #:use-module (gnu packages pkg-config)
    #:use-module (gnu packages xorg)
    #:use-module (gnu packages lesstif)
    #:use-module (gnu packages llvm)
    #:use-module (gnu packages image)
    #:use-module (gnu packages image-viewers)
    #:use-module (gnu packages linux)
    #:use-module (gnu packages libevent)
    #:use-module (gnu packages lisp)
    #:use-module (gnu packages lisp-xyz)
    #:use-module (gnu packages lsof)
    #:use-module (gnu packages lua)
    #:use-module (gnu packages maths)
    #:use-module (gnu packages music)
    #:use-module (gnu packages version-control)
    #:use-module (gnu packages imagemagick)
    #:use-module (gnu packages w3m)
    #:use-module (gnu packages web)
    #:use-module (gnu packages wget)
    #:use-module (gnu packages autotools)
    #:use-module (gnu packages base)
    #:use-module (gnu packages compression)
    #:use-module (gnu packages node)
    #:use-module (gnu packages xml)
    #:use-module (gnu packages glib)
    #:use-module (gnu packages acl)
    #:use-module (gnu packages mail)
    #:use-module (gnu packages messaging)
    #:use-module (gnu packages package-management)
    #:use-module (gnu packages perl)
    #:use-module (gnu packages pdf)
    #:use-module (gnu packages racket)
    #:use-module (gnu packages ruby)
    #:use-module (gnu packages rust)
    #:use-module (gnu packages rust-apps)
    #:use-module (gnu packages scheme)
    #:use-module (gnu packages serialization)
    #:use-module (gnu packages speech)
    #:use-module (gnu packages xiph)
    #:use-module (gnu packages mp3)
    #:use-module (gnu packages gettext)
    #:use-module (gnu packages fribidi)
    #:use-module (gnu packages gd)
    #:use-module (gnu packages fontutils)
    #:use-module (gnu packages password-utils)
    #:use-module (gnu packages pulseaudio)
    #:use-module (gnu packages animation)
    #:use-module (gnu packages sphinx)
    #:use-module (gnu packages screen)
    #:use-module (gnu packages xdisorg)
    #:use-module (gnu packages shells)
    #:use-module (gnu packages shellutils)
    #:use-module (gnu packages sqlite)
    #:use-module (gnu packages ghostscript)
    #:use-module (gnu packages gnupg)
    #:use-module (gnu packages video)
    #:use-module (gnu packages haskell-xyz)
    #:use-module (gnu packages wordnet)
    #:use-module (gnu packages photo)
    #:use-module (gnu packages tor)
    #:use-module (gnu packages uml)
    #:use-module (gnu packages finance)
    #:use-module (gnu packages ocaml)
    #:use-module (gnu packages erlang)
    #:use-module (gnu packages statistics)
    #:use-module (gnu packages libcanberra)
    #:use-module (gnu packages texinfo)
    #:use-module (gnu packages text-editors)
    #:use-module (gnu packages virtualization)
    #:use-module (gnu packages web-browsers)
    #:use-module (gnu packages wget)
    #:use-module (guix utils)
    #:use-module (srfi srfi-1)
    #:use-module (ice-9 match))

(define-public my-emacs-parinfer-rust-mode
  (package
    (name "my-emacs-parinfer-rust-mode")
    (version "0.9.3")
    (source
     (origin
       (method git-fetch)
       (uri (git-reference
             (url "https://github.com/justinbarclay/parinfer-rust-mode")
             (commit (string-append "v" version))))
       (file-name (git-file-name name version))
       (sha256
        (base32 "1p00m757maw6dxig0x45gry1l7vm9dm6wg1anfm2rwl6hw1f5q25"))))
    (build-system emacs-build-system)
    (arguments
     (list
      #:phases
      #~(modify-phases %standard-phases
          (add-after 'unpack 'configure
            (lambda* (#:key inputs #:allow-other-keys)
              (let ((parinfer-lib
                     (dirname
                      (search-input-file inputs "lib/libparinfer_rust.so"))))
                ;; Specify the absolute file names of the parinfer shared
                ;; library.
                ;; (make-file-writable "parinfer-rust-mode.el")
                (emacs-substitute-variables "parinfer-rust-mode.el"
                  ("parinfer-rust--lib-name" "libparinfer_rust.so")
                  ("parinfer-rust-library-dir" (string-append parinfer-lib "/test1")))
                (emacs-substitute-sexps "parinfer-rust-mode.el"
                  ("defcustom parinfer-rust-library-directory" (string-append parinfer-lib "/test2"))
                  ("defconst parinfer-rust--lib-name"
                   "libparinfer_rust.so"))))))))
    (inputs (list parinfer-rust-emacs))
    (propagated-inputs (list emacs-track-changes))
    (home-page "https://github.com/justinbarclay/parinfer-rust-mode")
    (synopsis "Lisp structure editing mode leveraging Parinfer Rust")
    (description
     "Parinfer Rust mode aims to be a simple implementation of Parinfer that
leverages the Parinfer Rust Emacs library to do most of the heavy lifting.")
    (license license:gpl3+)))
